### ISSUE TITLE
Enable ability to pull the image from somewhere other than docker

### ISSUE THREAD

**Issue by MattPOlson** [carlosedp/lbconfig-operator#124]
Since we don't have docker enterprise we get rate limited when trying to pull the container image. Would it be possible to add a feature so we can host the image in a internal repo and pull from there?

**Comment by carlosedp** [comment]
Hi, thanks for the report. This is a good feature which I look forward implementing within this week or the next.

**Comment by carlosedp** [comment]
Sorry about the long time to answer... I don't know how to make this work on the OperatorHub since the manifests are pre-built and loaded from there (with the image).

You could use the manual deployment using the `manifests/deploy.yaml` just changing the image to another registry. I've also pushed the image to Quay on //quay.io/carlosedp/lbconfig-operator:v0.4.0.

Let me know if it helped.

**Comment by carlosedp** [comment]
On this last version (0.4.1) the image has been pushed to Quay.io that don't impose rate-limiting. The image can be found on https://quay.io/repository/carlosedp/lbconfig-operator.
